-- Base domain schema: master data, time-series, alarm (DM8 / H2 compatible)
-- For dev (H2), enabled via spring.sql.init (see application.yml). For DM8, execute manually.

-- =========================
-- Master data (dimensions)
-- =========================
CREATE TABLE IF NOT EXISTS DIM_PARK (
    PARK_ID BIGINT IDENTITY PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    REGION VARCHAR(64),
    TIMEZONE VARCHAR(64) DEFAULT 'Asia/Shanghai' NOT NULL,
    BOUNDARY_GEOJSON CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DIM_ENTERPRISE (
    ENT_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    INDUSTRY VARCHAR(64),
    IS_KEY_USER CHAR(1) DEFAULT 'N' NOT NULL,
    CONTACT VARCHAR(128),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ENT_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE INDEX IF NOT EXISTS IDX_ENT_PARK ON DIM_ENTERPRISE(PARK_ID);

CREATE TABLE IF NOT EXISTS DIM_ENERGY_TYPE (
    ENERGY_TYPE_CODE VARCHAR(32) PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    CATEGORY VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS DIM_ASSET (
    ASSET_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    ENT_ID BIGINT,
    ASSET_TYPE VARCHAR(32) NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    VENDOR VARCHAR(64),
    MODEL_NO VARCHAR(64),
    RATED_CAPACITY DECIMAL(18,4),
    LOCATION_GEOJSON CLOB,
    STATUS VARCHAR(32),
    COMMISSION_DATE DATE,
    CONSTRAINT FK_ASSET_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID),
    CONSTRAINT FK_ASSET_ENT FOREIGN KEY (ENT_ID) REFERENCES DIM_ENTERPRISE(ENT_ID)
);
CREATE INDEX IF NOT EXISTS IDX_ASSET_PARK ON DIM_ASSET(PARK_ID);
CREATE INDEX IF NOT EXISTS IDX_ASSET_ENT ON DIM_ASSET(ENT_ID);

CREATE TABLE IF NOT EXISTS DIM_METER_POINT (
    POINT_ID BIGINT IDENTITY PRIMARY KEY,
    ASSET_ID BIGINT,
    ENT_ID BIGINT,
    PARK_ID BIGINT NOT NULL,
    ENERGY_TYPE VARCHAR(32),
    MEAS_TYPE VARCHAR(32),
    UNIT VARCHAR(16),
    SAMPLING_INTERVAL_S INT,
    PROTOCOL VARCHAR(32),
    TAG_ADDRESS VARCHAR(128),
    IS_CRITICAL CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT FK_POINT_ASSET FOREIGN KEY (ASSET_ID) REFERENCES DIM_ASSET(ASSET_ID),
    CONSTRAINT FK_POINT_ENT FOREIGN KEY (ENT_ID) REFERENCES DIM_ENTERPRISE(ENT_ID),
    CONSTRAINT FK_POINT_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID),
    CONSTRAINT FK_POINT_ENERGY_TYPE FOREIGN KEY (ENERGY_TYPE) REFERENCES DIM_ENERGY_TYPE(ENERGY_TYPE_CODE)
);
CREATE INDEX IF NOT EXISTS IDX_POINT_PARK ON DIM_METER_POINT(PARK_ID);
CREATE INDEX IF NOT EXISTS IDX_POINT_ASSET ON DIM_METER_POINT(ASSET_ID);
CREATE INDEX IF NOT EXISTS IDX_POINT_ENT ON DIM_METER_POINT(ENT_ID);

CREATE TABLE IF NOT EXISTS DIM_PRICE_ZONE (
    ZONE_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    GRID_COMPANY VARCHAR(128),
    TARIFF_RULE_VERSION VARCHAR(64),
    CONSTRAINT FK_PRICE_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE INDEX IF NOT EXISTS IDX_PRICE_PARK ON DIM_PRICE_ZONE(PARK_ID);

CREATE TABLE IF NOT EXISTS DIM_CARBON_FACTOR (
    FACTOR_ID BIGINT IDENTITY PRIMARY KEY,
    REGION VARCHAR(64),
    ENERGY_TYPE VARCHAR(32),
    FACTOR_VALUE DECIMAL(18,6) NOT NULL,
    UNIT VARCHAR(16) DEFAULT 'kg/kWh',
    EFFECTIVE_FROM DATE NOT NULL,
    EFFECTIVE_TO DATE,
    SOURCE VARCHAR(128),
    IS_DEFAULT CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT FK_CARBON_ENERGY_TYPE FOREIGN KEY (ENERGY_TYPE) REFERENCES DIM_ENERGY_TYPE(ENERGY_TYPE_CODE)
);
CREATE INDEX IF NOT EXISTS IDX_CARBON_REGION_TYPE ON DIM_CARBON_FACTOR(REGION, ENERGY_TYPE);

-- =========================
-- Time-series (facts)
-- =========================
CREATE TABLE IF NOT EXISTS RAW_TIMESERIES (
    ID BIGINT IDENTITY PRIMARY KEY,
    POINT_ID BIGINT NOT NULL,
    TS TIMESTAMP NOT NULL,
    VALUE DECIMAL(20,6),
    QUALITY_FLAG VARCHAR(32),
    SOURCE_SYSTEM VARCHAR(64),
    INGEST_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_RAW_POINT FOREIGN KEY (POINT_ID) REFERENCES DIM_METER_POINT(POINT_ID)
);
CREATE INDEX IF NOT EXISTS IDX_RAW_POINT_TS ON RAW_TIMESERIES(POINT_ID, TS);
CREATE INDEX IF NOT EXISTS IDX_RAW_TS ON RAW_TIMESERIES(TS);

CREATE TABLE IF NOT EXISTS TS_MEASUREMENT (
    ID BIGINT IDENTITY PRIMARY KEY,
    POINT_ID BIGINT NOT NULL,
    TS TIMESTAMP NOT NULL,
    VALUE DECIMAL(20,6),
    QUALITY_FLAG VARCHAR(32),
    AGG_LEVEL VARCHAR(16),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TS_POINT FOREIGN KEY (POINT_ID) REFERENCES DIM_METER_POINT(POINT_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_TS_POINT_TS ON TS_MEASUREMENT(POINT_ID, TS);
CREATE INDEX IF NOT EXISTS IDX_TS_TS ON TS_MEASUREMENT(TS);

-- =========================
-- Alarm / monitoring
-- =========================
CREATE TABLE IF NOT EXISTS CFG_ALARM_RULE (
    RULE_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    CATEGORY VARCHAR(64),
    EXPRESSION CLOB,
    THRESHOLD DECIMAL(18,6),
    SEVERITY VARCHAR(16),
    NOTIFICATION_GROUP VARCHAR(128),
    ENABLED CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT FK_RULE_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_RULE_PARK_NAME ON CFG_ALARM_RULE(PARK_ID, NAME);

CREATE TABLE IF NOT EXISTS EVT_ALARM (
    ALARM_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    ENT_ID BIGINT,
    ASSET_ID BIGINT,
    LEVEL VARCHAR(16),
    CATEGORY VARCHAR(64),
    OBJECT_TYPE VARCHAR(32),
    OBJECT_ID BIGINT,
    START_TS TIMESTAMP NOT NULL,
    END_TS TIMESTAMP,
    STATUS VARCHAR(16),
    RULE_ID BIGINT,
    MESSAGE CLOB,
    ACK_BY VARCHAR(64),
    ACK_TS TIMESTAMP,
    CONSTRAINT FK_ALARM_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID),
    CONSTRAINT FK_ALARM_ENT FOREIGN KEY (ENT_ID) REFERENCES DIM_ENTERPRISE(ENT_ID),
    CONSTRAINT FK_ALARM_ASSET FOREIGN KEY (ASSET_ID) REFERENCES DIM_ASSET(ASSET_ID),
    CONSTRAINT FK_ALARM_RULE FOREIGN KEY (RULE_ID) REFERENCES CFG_ALARM_RULE(RULE_ID)
);
CREATE INDEX IF NOT EXISTS IDX_ALARM_PARK_START ON EVT_ALARM(PARK_ID, START_TS);
CREATE INDEX IF NOT EXISTS IDX_ALARM_ASSET ON EVT_ALARM(ASSET_ID);

CREATE TABLE IF NOT EXISTS DEF_KEY_MONITOR_POINT (
    ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    POINT_ID BIGINT NOT NULL,
    POINT_NAME VARCHAR(128),
    CATEGORY VARCHAR(64),
    CONSTRAINT FK_MONITOR_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID),
    CONSTRAINT FK_MONITOR_POINT FOREIGN KEY (POINT_ID) REFERENCES DIM_METER_POINT(POINT_ID)
);
CREATE INDEX IF NOT EXISTS IDX_MONITOR_PARK ON DEF_KEY_MONITOR_POINT(PARK_ID);

CREATE TABLE IF NOT EXISTS EVT_ACTION_RECO (
    RECO_ID BIGINT IDENTITY PRIMARY KEY,
    ALARM_ID BIGINT NOT NULL,
    RECO_TYPE VARCHAR(32),
    COMMAND_TEMPLATE CLOB,
    PRIORITY INT,
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(16),
    CONSTRAINT FK_RECO_ALARM FOREIGN KEY (ALARM_ID) REFERENCES EVT_ALARM(ALARM_ID)
);
CREATE INDEX IF NOT EXISTS IDX_RECO_ALARM ON EVT_ACTION_RECO(ALARM_ID);

-- =========================
-- Source-side forecast (wind/solar)
-- =========================
CREATE TABLE IF NOT EXISTS WEATHER_STATION (
    STATION_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    LAT DECIMAL(10,6),
    LON DECIMAL(10,6),
    ELEVATION DECIMAL(10,2),
    PROVIDER VARCHAR(64),
    STATUS VARCHAR(16),
    CONSTRAINT FK_WEATHER_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE INDEX IF NOT EXISTS IDX_WEATHER_PARK ON WEATHER_STATION(PARK_ID);

CREATE TABLE IF NOT EXISTS WEATHER_OBS (
    ID BIGINT IDENTITY PRIMARY KEY,
    STATION_ID BIGINT NOT NULL,
    TS TIMESTAMP NOT NULL,
    TEMPERATURE DECIMAL(10,4),
    WIND_SPEED DECIMAL(10,4),
    WIND_DIR DECIMAL(10,2),
    GHI DECIMAL(10,4),
    DNI DECIMAL(10,4),
    DHI DECIMAL(10,4),
    HUMIDITY DECIMAL(10,4),
    PRESSURE DECIMAL(10,4),
    QUALITY_FLAG VARCHAR(32),
    CONSTRAINT FK_OBS_STATION FOREIGN KEY (STATION_ID) REFERENCES WEATHER_STATION(STATION_ID)
);
CREATE INDEX IF NOT EXISTS IDX_OBS_STATION_TS ON WEATHER_OBS(STATION_ID, TS);

CREATE TABLE IF NOT EXISTS WEATHER_FORECAST (
    ID BIGINT IDENTITY PRIMARY KEY,
    STATION_ID BIGINT NOT NULL,
    FORECAST_ISSUE_TS TIMESTAMP NOT NULL,
    TS TIMESTAMP NOT NULL,
    TEMPERATURE_PRED DECIMAL(10,4),
    WIND_SPEED_PRED DECIMAL(10,4),
    GHI_PRED DECIMAL(10,4),
    DNI_PRED DECIMAL(10,4),
    CLOUD_COVER_PRED DECIMAL(10,4),
    MODEL_NAME VARCHAR(64),
    CONSTRAINT FK_FORECAST_STATION FOREIGN KEY (STATION_ID) REFERENCES WEATHER_STATION(STATION_ID)
);
CREATE INDEX IF NOT EXISTS IDX_FORECAST_STATION_TS ON WEATHER_FORECAST(STATION_ID, TS);
CREATE INDEX IF NOT EXISTS IDX_FORECAST_ISSUE ON WEATHER_FORECAST(FORECAST_ISSUE_TS);

CREATE TABLE IF NOT EXISTS MAP_ASSET_WEATHER (
    ASSET_ID BIGINT NOT NULL,
    STATION_ID BIGINT NOT NULL,
    WEIGHT DECIMAL(10,4) DEFAULT 1.0,
    EFFECTIVE_FROM DATE,
    EFFECTIVE_TO DATE,
    CONSTRAINT PK_MAP_ASSET_WEATHER PRIMARY KEY (ASSET_ID, STATION_ID),
    CONSTRAINT FK_MAP_ASSET FOREIGN KEY (ASSET_ID) REFERENCES DIM_ASSET(ASSET_ID),
    CONSTRAINT FK_MAP_STATION FOREIGN KEY (STATION_ID) REFERENCES WEATHER_STATION(STATION_ID)
);

CREATE TABLE IF NOT EXISTS GEN_FORECAST (
    ID BIGINT IDENTITY PRIMARY KEY,
    ASSET_ID BIGINT NOT NULL,
    FORECAST_ISSUE_TS TIMESTAMP NOT NULL,
    TS TIMESTAMP NOT NULL,
    P_KW_PRED DECIMAL(18,4),
    P10 DECIMAL(18,4),
    P90 DECIMAL(18,4),
    MODEL_VERSION VARCHAR(64),
    SCENARIO VARCHAR(32),
    CONSTRAINT FK_GEN_FORECAST_ASSET FOREIGN KEY (ASSET_ID) REFERENCES DIM_ASSET(ASSET_ID)
);
CREATE INDEX IF NOT EXISTS IDX_GEN_FORECAST_ASSET_TS ON GEN_FORECAST(ASSET_ID, TS);
CREATE INDEX IF NOT EXISTS IDX_GEN_FORECAST_ISSUE ON GEN_FORECAST(FORECAST_ISSUE_TS);

CREATE TABLE IF NOT EXISTS LOG_FORECAST_EVAL (
    EVAL_ID BIGINT IDENTITY PRIMARY KEY,
    ASSET_ID BIGINT NOT NULL,
    FORECAST_ISSUE_TS TIMESTAMP NOT NULL,
    HORIZON_MIN INT,
    MAE DECIMAL(18,6),
    MAPE DECIMAL(18,6),
    BIAS DECIMAL(18,6),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_FORECAST_EVAL_ASSET FOREIGN KEY (ASSET_ID) REFERENCES DIM_ASSET(ASSET_ID)
);
CREATE INDEX IF NOT EXISTS IDX_FORECAST_EVAL_ASSET ON LOG_FORECAST_EVAL(ASSET_ID);

-- =========================
-- Microgrid topology & control (net-side)
-- =========================
CREATE TABLE IF NOT EXISTS MG_BUS (
    BUS_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    VOLTAGE_LEVEL_KV DECIMAL(10,3),
    BUS_TYPE VARCHAR(32),
    CONSTRAINT FK_MG_BUS_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE INDEX IF NOT EXISTS IDX_MG_BUS_PARK ON MG_BUS(PARK_ID);

CREATE TABLE IF NOT EXISTS MG_LINE (
    LINE_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    FROM_BUS_ID BIGINT NOT NULL,
    TO_BUS_ID BIGINT NOT NULL,
    R_OHM DECIMAL(18,6),
    X_OHM DECIMAL(18,6),
    CAPACITY_A DECIMAL(18,4),
    CONSTRAINT FK_MG_LINE_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID),
    CONSTRAINT FK_MG_LINE_FROM FOREIGN KEY (FROM_BUS_ID) REFERENCES MG_BUS(BUS_ID),
    CONSTRAINT FK_MG_LINE_TO FOREIGN KEY (TO_BUS_ID) REFERENCES MG_BUS(BUS_ID)
);
CREATE INDEX IF NOT EXISTS IDX_MG_LINE_PARK ON MG_LINE(PARK_ID);

CREATE TABLE IF NOT EXISTS MG_TRANSFORMER (
    TF_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    HV_BUS_ID BIGINT NOT NULL,
    LV_BUS_ID BIGINT NOT NULL,
    RATED_KVA DECIMAL(18,4),
    IMPEDANCE_PERCENT DECIMAL(10,4),
    CONSTRAINT FK_MG_TF_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID),
    CONSTRAINT FK_MG_TF_HV FOREIGN KEY (HV_BUS_ID) REFERENCES MG_BUS(BUS_ID),
    CONSTRAINT FK_MG_TF_LV FOREIGN KEY (LV_BUS_ID) REFERENCES MG_BUS(BUS_ID)
);
CREATE INDEX IF NOT EXISTS IDX_MG_TF_PARK ON MG_TRANSFORMER(PARK_ID);

CREATE TABLE IF NOT EXISTS MG_SWITCH (
    SW_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    FROM_BUS_ID BIGINT NOT NULL,
    TO_BUS_ID BIGINT NOT NULL,
    POINT_ID_STATUS BIGINT,
    NORMAL_STATE VARCHAR(16),
    CONSTRAINT FK_MG_SW_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID),
    CONSTRAINT FK_MG_SW_FROM FOREIGN KEY (FROM_BUS_ID) REFERENCES MG_BUS(BUS_ID),
    CONSTRAINT FK_MG_SW_TO FOREIGN KEY (TO_BUS_ID) REFERENCES MG_BUS(BUS_ID),
    CONSTRAINT FK_MG_SW_POINT FOREIGN KEY (POINT_ID_STATUS) REFERENCES DIM_METER_POINT(POINT_ID)
);
CREATE INDEX IF NOT EXISTS IDX_MG_SW_PARK ON MG_SWITCH(PARK_ID);

CREATE TABLE IF NOT EXISTS MG_CONNECTION_POINT (
    PCC_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    BUS_ID BIGINT NOT NULL,
    POINT_ID_P BIGINT,
    POINT_ID_Q BIGINT,
    POINT_ID_FREQ BIGINT,
    CONTRACT_CAPACITY_KW DECIMAL(18,4),
    CONSTRAINT FK_MG_PCC_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID),
    CONSTRAINT FK_MG_PCC_BUS FOREIGN KEY (BUS_ID) REFERENCES MG_BUS(BUS_ID),
    CONSTRAINT FK_MG_PCC_P FOREIGN KEY (POINT_ID_P) REFERENCES DIM_METER_POINT(POINT_ID),
    CONSTRAINT FK_MG_PCC_Q FOREIGN KEY (POINT_ID_Q) REFERENCES DIM_METER_POINT(POINT_ID),
    CONSTRAINT FK_MG_PCC_FREQ FOREIGN KEY (POINT_ID_FREQ) REFERENCES DIM_METER_POINT(POINT_ID)
);
CREATE INDEX IF NOT EXISTS IDX_MG_PCC_PARK ON MG_CONNECTION_POINT(PARK_ID);

CREATE TABLE IF NOT EXISTS MG_RUNTIME_STATE (
    ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    TS TIMESTAMP NOT NULL,
    MODE VARCHAR(32),
    ISLAND_FLAG CHAR(1),
    P_TOTAL_KW DECIMAL(18,4),
    Q_TOTAL_KVAR DECIMAL(18,4),
    FREQ_HZ DECIMAL(10,4),
    SPINNING_RESERVE_KW DECIMAL(18,4),
    CONSTRAINT FK_MG_STATE_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE INDEX IF NOT EXISTS IDX_MG_STATE_PARK_TS ON MG_RUNTIME_STATE(PARK_ID, TS);

CREATE TABLE IF NOT EXISTS MG_CONTROL_COMMAND (
    CMD_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    TS_ISSUE TIMESTAMP NOT NULL,
    TARGET_ASSET_ID BIGINT,
    CMD_TYPE VARCHAR(64),
    PAYLOAD_JSON CLOB,
    STATUS VARCHAR(32),
    ISSUED_BY VARCHAR(64),
    CONSTRAINT FK_MG_CMD_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID),
    CONSTRAINT FK_MG_CMD_ASSET FOREIGN KEY (TARGET_ASSET_ID) REFERENCES DIM_ASSET(ASSET_ID)
);
CREATE INDEX IF NOT EXISTS IDX_MG_CMD_PARK_TS ON MG_CONTROL_COMMAND(PARK_ID, TS_ISSUE);

CREATE TABLE IF NOT EXISTS MG_COMMAND_RESULT (
    RESULT_ID BIGINT IDENTITY PRIMARY KEY,
    CMD_ID BIGINT NOT NULL,
    TS_FEEDBACK TIMESTAMP,
    IS_SUCCESS CHAR(1),
    MESSAGE VARCHAR(512),
    TELEMETRY_SNAPSHOT_JSON CLOB,
    CONSTRAINT FK_MG_RESULT_CMD FOREIGN KEY (CMD_ID) REFERENCES MG_CONTROL_COMMAND(CMD_ID)
);
CREATE INDEX IF NOT EXISTS IDX_MG_RESULT_CMD ON MG_COMMAND_RESULT(CMD_ID);

-- =========================
-- Dispatch / constraints (multi-energy)
-- =========================
CREATE TABLE IF NOT EXISTS ASSET_DYNAMIC_CAPABILITY (
    ID BIGINT IDENTITY PRIMARY KEY,
    ASSET_ID BIGINT NOT NULL,
    TS TIMESTAMP NOT NULL,
    AVAILABLE_KW DECIMAL(18,4),
    RAMP_UP_KW_PER_MIN DECIMAL(18,4),
    RAMP_DOWN_KW_PER_MIN DECIMAL(18,4),
    STATUS VARCHAR(32),
    CONSTRAINT FK_CAP_ASSET FOREIGN KEY (ASSET_ID) REFERENCES DIM_ASSET(ASSET_ID)
);
CREATE INDEX IF NOT EXISTS IDX_CAP_ASSET_TS ON ASSET_DYNAMIC_CAPABILITY(ASSET_ID, TS);

CREATE TABLE IF NOT EXISTS CFG_MULTI_ENERGY_MODEL (
    MODEL_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    FROM_ENERGY VARCHAR(32),
    TO_ENERGY VARCHAR(32),
    ASSET_ID BIGINT,
    EFFICIENCY_FORMULA VARCHAR(256),
    CONSTRAINT FK_MULTI_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID),
    CONSTRAINT FK_MULTI_ASSET FOREIGN KEY (ASSET_ID) REFERENCES DIM_ASSET(ASSET_ID)
);
CREATE INDEX IF NOT EXISTS IDX_MULTI_PARK ON CFG_MULTI_ENERGY_MODEL(PARK_ID);

CREATE TABLE IF NOT EXISTS CFG_DISPATCH_CONSTRAINT (
    CONSTRAINT_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    EXPRESSION CLOB,
    CATEGORY VARCHAR(64),
    ENABLED CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT FK_DISPATCH_CONSTRAINT_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_DISPATCH_CONSTRAINT ON CFG_DISPATCH_CONSTRAINT(PARK_ID, NAME);

CREATE TABLE IF NOT EXISTS DISPATCH_PLAN (
    PLAN_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    HORIZON_START TIMESTAMP NOT NULL,
    HORIZON_END TIMESTAMP NOT NULL,
    INTERVAL_MIN INT,
    STRATEGY_PROFILE_ID BIGINT,
    STATUS VARCHAR(32),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_PLAN_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE INDEX IF NOT EXISTS IDX_PLAN_PARK ON DISPATCH_PLAN(PARK_ID);

CREATE TABLE IF NOT EXISTS DISPATCH_PLAN_DETAIL (
    ID BIGINT IDENTITY PRIMARY KEY,
    PLAN_ID BIGINT NOT NULL,
    TS TIMESTAMP NOT NULL,
    ASSET_ID BIGINT NOT NULL,
    P_SET_KW DECIMAL(18,4),
    Q_SET_KVAR DECIMAL(18,4),
    HEAT_SET_MW DECIMAL(18,4),
    SOC_TARGET DECIMAL(10,4),
    CONSTRAINT FK_PLAN_DETAIL_PLAN FOREIGN KEY (PLAN_ID) REFERENCES DISPATCH_PLAN(PLAN_ID),
    CONSTRAINT FK_PLAN_DETAIL_ASSET FOREIGN KEY (ASSET_ID) REFERENCES DIM_ASSET(ASSET_ID)
);
CREATE INDEX IF NOT EXISTS IDX_PLAN_DETAIL_PLAN_TS ON DISPATCH_PLAN_DETAIL(PLAN_ID, TS);
CREATE INDEX IF NOT EXISTS IDX_PLAN_DETAIL_ASSET ON DISPATCH_PLAN_DETAIL(ASSET_ID);

CREATE TABLE IF NOT EXISTS DISPATCH_INSTRUCTION (
    INS_ID BIGINT IDENTITY PRIMARY KEY,
    PLAN_ID BIGINT NOT NULL,
    TS_ISSUE TIMESTAMP NOT NULL,
    ASSET_ID BIGINT NOT NULL,
    CMD_TYPE VARCHAR(64),
    SET_VALUE DECIMAL(18,4),
    UNIT VARCHAR(16),
    STATUS VARCHAR(32),
    ACK_TS TIMESTAMP,
    CONSTRAINT FK_DISPATCH_INS_PLAN FOREIGN KEY (PLAN_ID) REFERENCES DISPATCH_PLAN(PLAN_ID),
    CONSTRAINT FK_DISPATCH_INS_ASSET FOREIGN KEY (ASSET_ID) REFERENCES DIM_ASSET(ASSET_ID)
);
CREATE INDEX IF NOT EXISTS IDX_DISPATCH_INS_PLAN ON DISPATCH_INSTRUCTION(PLAN_ID);
CREATE INDEX IF NOT EXISTS IDX_DISPATCH_INS_ASSET ON DISPATCH_INSTRUCTION(ASSET_ID);

-- =========================
-- Load forecast (park/enterprise)
-- =========================
CREATE TABLE IF NOT EXISTS PRODUCTION_PLAN (
    PLAN_ID BIGINT IDENTITY PRIMARY KEY,
    ENT_ID BIGINT NOT NULL,
    PLAN_DATE DATE NOT NULL,
    SHIFT_INFO_JSON CLOB,
    MAINTENANCE_ASSETS_JSON CLOB,
    STATUS VARCHAR(32),
    SUBMITTED_TS TIMESTAMP,
    CONSTRAINT FK_PROD_PLAN_ENT FOREIGN KEY (ENT_ID) REFERENCES DIM_ENTERPRISE(ENT_ID)
);
CREATE INDEX IF NOT EXISTS IDX_PROD_PLAN_ENT_DATE ON PRODUCTION_PLAN(ENT_ID, PLAN_DATE);

CREATE TABLE IF NOT EXISTS DIM_CALENDAR (
    CAL_DATE DATE PRIMARY KEY,
    DAY_OF_WEEK INT,
    IS_HOLIDAY CHAR(1),
    IS_WORKDAY CHAR(1)
);

CREATE TABLE IF NOT EXISTS LOAD_FORECAST (
    ID BIGINT IDENTITY PRIMARY KEY,
    ENT_ID BIGINT NOT NULL,
    FORECAST_ISSUE_TS TIMESTAMP NOT NULL,
    TS TIMESTAMP NOT NULL,
    P_KW_PRED DECIMAL(18,4),
    P10 DECIMAL(18,4),
    P90 DECIMAL(18,4),
    MODEL_VERSION VARCHAR(64),
    CONSTRAINT FK_LOAD_FORECAST_ENT FOREIGN KEY (ENT_ID) REFERENCES DIM_ENTERPRISE(ENT_ID)
);
CREATE INDEX IF NOT EXISTS IDX_LOAD_FORECAST_ENT_TS ON LOAD_FORECAST(ENT_ID, TS);
CREATE INDEX IF NOT EXISTS IDX_LOAD_FORECAST_ISSUE ON LOAD_FORECAST(FORECAST_ISSUE_TS);

CREATE TABLE IF NOT EXISTS LOG_LOAD_ANOMALY (
    ID BIGINT IDENTITY PRIMARY KEY,
    ENT_ID BIGINT NOT NULL,
    TS TIMESTAMP NOT NULL,
    ANOMALY_TYPE VARCHAR(64),
    SCORE DECIMAL(18,6),
    MESSAGE VARCHAR(512),
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_LOAD_ANOMALY_ENT FOREIGN KEY (ENT_ID) REFERENCES DIM_ENTERPRISE(ENT_ID)
);
CREATE INDEX IF NOT EXISTS IDX_LOAD_ANOMALY_ENT_TS ON LOG_LOAD_ANOMALY(ENT_ID, TS);

-- =========================
-- Demand response & VPP
-- =========================
CREATE TABLE IF NOT EXISTS DR_RESOURCE (
    RES_ID BIGINT IDENTITY PRIMARY KEY,
    ENT_ID BIGINT NOT NULL,
    ASSET_ID BIGINT,
    RES_TYPE VARCHAR(32),
    CAPACITY_KW DECIMAL(18,4),
    RESPONSE_TIME_S INT,
    MIN_DURATION_MIN INT,
    AVAILABILITY_SCHEDULE CLOB,
    BASELINE_METHOD VARCHAR(64),
    ENABLED CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT FK_DR_RESOURCE_ENT FOREIGN KEY (ENT_ID) REFERENCES DIM_ENTERPRISE(ENT_ID),
    CONSTRAINT FK_DR_RESOURCE_ASSET FOREIGN KEY (ASSET_ID) REFERENCES DIM_ASSET(ASSET_ID)
);
CREATE INDEX IF NOT EXISTS IDX_DR_RESOURCE_ENT ON DR_RESOURCE(ENT_ID);

CREATE TABLE IF NOT EXISTS DR_EVENT (
    EVENT_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    EVENT_TYPE VARCHAR(32),
    START_TS TIMESTAMP NOT NULL,
    END_TS TIMESTAMP NOT NULL,
    TARGET_KW DECIMAL(18,4),
    PRICE_SIGNAL DECIMAL(18,4),
    STATUS VARCHAR(32),
    ISSUED_BY VARCHAR(64),
    ISSUED_TS TIMESTAMP,
    CONSTRAINT FK_DR_EVENT_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE INDEX IF NOT EXISTS IDX_DR_EVENT_PARK_START ON DR_EVENT(PARK_ID, START_TS);

CREATE TABLE IF NOT EXISTS DR_PARTICIPATION (
    ID BIGINT IDENTITY PRIMARY KEY,
    EVENT_ID BIGINT NOT NULL,
    RES_ID BIGINT NOT NULL,
    COMMITTED_KW DECIMAL(18,4),
    CONFIRMED_FLAG CHAR(1),
    CONFIRM_TS TIMESTAMP,
    STATUS VARCHAR(32),
    CONSTRAINT FK_DR_PART_EVENT FOREIGN KEY (EVENT_ID) REFERENCES DR_EVENT(EVENT_ID),
    CONSTRAINT FK_DR_PART_RES FOREIGN KEY (RES_ID) REFERENCES DR_RESOURCE(RES_ID)
);
CREATE INDEX IF NOT EXISTS IDX_DR_PART_EVENT ON DR_PARTICIPATION(EVENT_ID);
CREATE INDEX IF NOT EXISTS IDX_DR_PART_RES ON DR_PARTICIPATION(RES_ID);

CREATE TABLE IF NOT EXISTS DR_PERFORMANCE (
    ID BIGINT IDENTITY PRIMARY KEY,
    EVENT_ID BIGINT NOT NULL,
    RES_ID BIGINT NOT NULL,
    TS TIMESTAMP NOT NULL,
    ACTUAL_KW DECIMAL(18,4),
    BASELINE_KW DECIMAL(18,4),
    DELIVERED_KW DECIMAL(18,4),
    CONSTRAINT FK_DR_PERF_EVENT FOREIGN KEY (EVENT_ID) REFERENCES DR_EVENT(EVENT_ID),
    CONSTRAINT FK_DR_PERF_RES FOREIGN KEY (RES_ID) REFERENCES DR_RESOURCE(RES_ID)
);
CREATE INDEX IF NOT EXISTS IDX_DR_PERF_EVENT_TS ON DR_PERFORMANCE(EVENT_ID, TS);

CREATE TABLE IF NOT EXISTS DR_SETTLEMENT (
    SETTLE_ID BIGINT IDENTITY PRIMARY KEY,
    EVENT_ID BIGINT NOT NULL,
    RES_ID BIGINT NOT NULL,
    DELIVERED_KWH DECIMAL(18,4),
    SETTLEMENT_AMOUNT DECIMAL(18,4),
    CURRENCY VARCHAR(16),
    STATUS VARCHAR(32),
    CONSTRAINT FK_DR_SETTLE_EVENT FOREIGN KEY (EVENT_ID) REFERENCES DR_EVENT(EVENT_ID),
    CONSTRAINT FK_DR_SETTLE_RES FOREIGN KEY (RES_ID) REFERENCES DR_RESOURCE(RES_ID)
);
CREATE INDEX IF NOT EXISTS IDX_DR_SETTLE_EVENT ON DR_SETTLEMENT(EVENT_ID);

CREATE TABLE IF NOT EXISTS VPP_AGGREGATOR (
    AGG_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    CAPACITY_UP_KW DECIMAL(18,4),
    CAPACITY_DOWN_KW DECIMAL(18,4),
    STATUS VARCHAR(32),
    CONSTRAINT FK_VPP_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE INDEX IF NOT EXISTS IDX_VPP_PARK ON VPP_AGGREGATOR(PARK_ID);

CREATE TABLE IF NOT EXISTS VPP_INTERFACE_LOG (
    LOG_ID BIGINT IDENTITY PRIMARY KEY,
    DIRECTION VARCHAR(16),
    PAYLOAD_JSON CLOB,
    TS TIMESTAMP NOT NULL,
    STATUS VARCHAR(32)
);
CREATE INDEX IF NOT EXISTS IDX_VPP_LOG_TS ON VPP_INTERFACE_LOG(TS);

-- =========================
-- Storage coordination
-- =========================
CREATE TABLE IF NOT EXISTS STORAGE_ASSET_EXT (
    ASSET_ID BIGINT PRIMARY KEY,
    ENERGY_KWH DECIMAL(18,4),
    POWER_KW DECIMAL(18,4),
    SOC_MIN DECIMAL(10,4),
    SOC_MAX DECIMAL(10,4),
    CHARGE_EFF DECIMAL(10,4),
    DISCHARGE_EFF DECIMAL(10,4),
    CYCLE_DEGRADE_COST_PER_KWH DECIMAL(18,6),
    VENDOR VARCHAR(64),
    CONSTRAINT FK_STORAGE_ASSET FOREIGN KEY (ASSET_ID) REFERENCES DIM_ASSET(ASSET_ID)
);

CREATE TABLE IF NOT EXISTS STORAGE_STATE (
    ID BIGINT IDENTITY PRIMARY KEY,
    ASSET_ID BIGINT NOT NULL,
    TS TIMESTAMP NOT NULL,
    SOC_PERCENT DECIMAL(10,4),
    SOH_PERCENT DECIMAL(10,4),
    P_KW DECIMAL(18,4),
    TEMP_C DECIMAL(10,4),
    HEALTH_STATUS VARCHAR(32),
    AVAILABLE_CHARGE_KW DECIMAL(18,4),
    AVAILABLE_DISCHARGE_KW DECIMAL(18,4),
    CONSTRAINT FK_STORAGE_STATE_ASSET FOREIGN KEY (ASSET_ID) REFERENCES DIM_ASSET(ASSET_ID)
);
CREATE INDEX IF NOT EXISTS IDX_STORAGE_STATE_ASSET_TS ON STORAGE_STATE(ASSET_ID, TS);

CREATE TABLE IF NOT EXISTS CFG_STORAGE_POLICY (
    POLICY_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    MODE VARCHAR(32),
    SOC_TARGET_MIN DECIMAL(10,4),
    SOC_TARGET_MAX DECIMAL(10,4),
    RESERVE_FOR_BLACKSTART_KW DECIMAL(18,4),
    PARTICIPATE_IN_FREQ_REG CHAR(1),
    ENABLED CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT FK_STORAGE_POLICY_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE INDEX IF NOT EXISTS IDX_STORAGE_POLICY_PARK ON CFG_STORAGE_POLICY(PARK_ID);

-- =========================
-- Price / carbon intensity slots
-- =========================
CREATE TABLE IF NOT EXISTS PRICE_TIMESLOT (
    ID BIGINT IDENTITY PRIMARY KEY,
    ZONE_ID BIGINT NOT NULL,
    START_TS TIMESTAMP NOT NULL,
    END_TS TIMESTAMP NOT NULL,
    PRICE_PER_KWH DECIMAL(18,6),
    PRICE_TYPE VARCHAR(32),
    CONSTRAINT FK_PRICE_SLOT_ZONE FOREIGN KEY (ZONE_ID) REFERENCES DIM_PRICE_ZONE(ZONE_ID)
);
CREATE INDEX IF NOT EXISTS IDX_PRICE_SLOT_ZONE_TS ON PRICE_TIMESLOT(ZONE_ID, START_TS);

CREATE TABLE IF NOT EXISTS CARBON_INTENSITY_TIMESLOT (
    ID BIGINT IDENTITY PRIMARY KEY,
    REGION VARCHAR(64),
    TS TIMESTAMP NOT NULL,
    GRID_CARBON_FACTOR_G_PER_KWH DECIMAL(18,6),
    SOURCE VARCHAR(128)
);
CREATE INDEX IF NOT EXISTS IDX_CARBON_INTENSITY_REGION_TS ON CARBON_INTENSITY_TIMESLOT(REGION, TS);

-- =========================
-- Strategy brain & carbon accounting
-- =========================
CREATE TABLE IF NOT EXISTS STRATEGY_PROFILE (
    PROFILE_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    MODE VARCHAR(32),
    OBJECTIVE_WEIGHTS_JSON CLOB,
    PRIORITY_ORDER_JSON CLOB,
    ENABLED CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT FK_STRATEGY_PROFILE_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_STRATEGY_PROFILE ON STRATEGY_PROFILE(PARK_ID, NAME);

CREATE TABLE IF NOT EXISTS CFG_CONSTRAINT_SET (
    SET_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    CONSTRAINTS_JSON CLOB,
    ENABLED CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT FK_CONSTRAINT_SET_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_CONSTRAINT_SET ON CFG_CONSTRAINT_SET(PARK_ID, NAME);

CREATE TABLE IF NOT EXISTS KPI_SIMULATION_RESULT (
    ID BIGINT IDENTITY PRIMARY KEY,
    PLAN_ID BIGINT NOT NULL,
    PROFILE_ID BIGINT,
    SIMULATED_COST DECIMAL(18,4),
    SIMULATED_CARBON DECIMAL(18,4),
    SIMULATED_RISK_SCORE DECIMAL(18,4),
    PASS_FLAG CHAR(1),
    CONSTRAINT FK_KPI_PLAN FOREIGN KEY (PLAN_ID) REFERENCES DISPATCH_PLAN(PLAN_ID),
    CONSTRAINT FK_KPI_PROFILE FOREIGN KEY (PROFILE_ID) REFERENCES STRATEGY_PROFILE(PROFILE_ID)
);
CREATE INDEX IF NOT EXISTS IDX_KPI_PLAN ON KPI_SIMULATION_RESULT(PLAN_ID);

CREATE TABLE IF NOT EXISTS FACT_CARBON_ACCOUNTING (
    ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    PERIOD_START TIMESTAMP NOT NULL,
    PERIOD_END TIMESTAMP NOT NULL,
    TOTAL_ENERGY_KWH DECIMAL(18,6),
    TOTAL_CARBON_KG DECIMAL(18,6),
    CARBON_ENERGY_RATIO DECIMAL(18,6),
    METHOD_VERSION VARCHAR(64),
    STATUS VARCHAR(32),
    CONSTRAINT FK_CARBON_ACCOUNT_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE INDEX IF NOT EXISTS IDX_CARBON_ACCOUNT_PARK ON FACT_CARBON_ACCOUNTING(PARK_ID);

CREATE TABLE IF NOT EXISTS FACT_CARBON_ACCOUNTING_DETAIL (
    ID BIGINT IDENTITY PRIMARY KEY,
    ACCOUNTING_ID BIGINT NOT NULL,
    ENT_ID BIGINT,
    ENERGY_TYPE VARCHAR(32),
    ENERGY_AMOUNT DECIMAL(18,6),
    FACTOR_USED DECIMAL(18,6),
    CARBON_AMOUNT DECIMAL(18,6),
    SOURCE_DESCRIPTION VARCHAR(256),
    CONSTRAINT FK_CARBON_DETAIL_ACCOUNT FOREIGN KEY (ACCOUNTING_ID) REFERENCES FACT_CARBON_ACCOUNTING(ID),
    CONSTRAINT FK_CARBON_DETAIL_ENT FOREIGN KEY (ENT_ID) REFERENCES DIM_ENTERPRISE(ENT_ID),
    CONSTRAINT FK_CARBON_DETAIL_ENERGY FOREIGN KEY (ENERGY_TYPE) REFERENCES DIM_ENERGY_TYPE(ENERGY_TYPE_CODE)
);
CREATE INDEX IF NOT EXISTS IDX_CARBON_DETAIL_ACCOUNT ON FACT_CARBON_ACCOUNTING_DETAIL(ACCOUNTING_ID);
