-- Base domain schema: master data, time-series, alarm (DM8 / H2 compatible)
-- For dev (H2), enabled via spring.sql.init (see application.yml). For DM8, execute manually.

-- =========================
-- Master data (dimensions)
-- =========================
CREATE TABLE IF NOT EXISTS DIM_PARK (
    PARK_ID BIGINT IDENTITY PRIMARY KEY,
    NAME VARCHAR(128) NOT NULL,
    REGION VARCHAR(64),
    TIMEZONE VARCHAR(64) DEFAULT 'Asia/Shanghai' NOT NULL,
    BOUNDARY_GEOJSON CLOB,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS DIM_ENTERPRISE (
    ENT_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    INDUSTRY VARCHAR(64),
    IS_KEY_USER CHAR(1) DEFAULT 'N' NOT NULL,
    CONTACT VARCHAR(128),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_ENT_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE INDEX IF NOT EXISTS IDX_ENT_PARK ON DIM_ENTERPRISE(PARK_ID);

CREATE TABLE IF NOT EXISTS DIM_ENERGY_TYPE (
    ENERGY_TYPE_CODE VARCHAR(32) PRIMARY KEY,
    NAME VARCHAR(64) NOT NULL,
    CATEGORY VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS DIM_ASSET (
    ASSET_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    ENT_ID BIGINT,
    ASSET_TYPE VARCHAR(32) NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    VENDOR VARCHAR(64),
    MODEL_NO VARCHAR(64),
    RATED_CAPACITY DECIMAL(18,4),
    LOCATION_GEOJSON CLOB,
    STATUS VARCHAR(32),
    COMMISSION_DATE DATE,
    CONSTRAINT FK_ASSET_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID),
    CONSTRAINT FK_ASSET_ENT FOREIGN KEY (ENT_ID) REFERENCES DIM_ENTERPRISE(ENT_ID)
);
CREATE INDEX IF NOT EXISTS IDX_ASSET_PARK ON DIM_ASSET(PARK_ID);
CREATE INDEX IF NOT EXISTS IDX_ASSET_ENT ON DIM_ASSET(ENT_ID);

CREATE TABLE IF NOT EXISTS DIM_METER_POINT (
    POINT_ID BIGINT IDENTITY PRIMARY KEY,
    ASSET_ID BIGINT,
    ENT_ID BIGINT,
    PARK_ID BIGINT NOT NULL,
    ENERGY_TYPE VARCHAR(32),
    MEAS_TYPE VARCHAR(32),
    UNIT VARCHAR(16),
    SAMPLING_INTERVAL_S INT,
    PROTOCOL VARCHAR(32),
    TAG_ADDRESS VARCHAR(128),
    IS_CRITICAL CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT FK_POINT_ASSET FOREIGN KEY (ASSET_ID) REFERENCES DIM_ASSET(ASSET_ID),
    CONSTRAINT FK_POINT_ENT FOREIGN KEY (ENT_ID) REFERENCES DIM_ENTERPRISE(ENT_ID),
    CONSTRAINT FK_POINT_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID),
    CONSTRAINT FK_POINT_ENERGY_TYPE FOREIGN KEY (ENERGY_TYPE) REFERENCES DIM_ENERGY_TYPE(ENERGY_TYPE_CODE)
);
CREATE INDEX IF NOT EXISTS IDX_POINT_PARK ON DIM_METER_POINT(PARK_ID);
CREATE INDEX IF NOT EXISTS IDX_POINT_ASSET ON DIM_METER_POINT(ASSET_ID);
CREATE INDEX IF NOT EXISTS IDX_POINT_ENT ON DIM_METER_POINT(ENT_ID);

CREATE TABLE IF NOT EXISTS DIM_PRICE_ZONE (
    ZONE_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    GRID_COMPANY VARCHAR(128),
    TARIFF_RULE_VERSION VARCHAR(64),
    CONSTRAINT FK_PRICE_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE INDEX IF NOT EXISTS IDX_PRICE_PARK ON DIM_PRICE_ZONE(PARK_ID);

CREATE TABLE IF NOT EXISTS DIM_CARBON_FACTOR (
    FACTOR_ID BIGINT IDENTITY PRIMARY KEY,
    REGION VARCHAR(64),
    ENERGY_TYPE VARCHAR(32),
    FACTOR_VALUE DECIMAL(18,6) NOT NULL,
    UNIT VARCHAR(16) DEFAULT 'kg/kWh',
    EFFECTIVE_FROM DATE NOT NULL,
    EFFECTIVE_TO DATE,
    SOURCE VARCHAR(128),
    IS_DEFAULT CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT FK_CARBON_ENERGY_TYPE FOREIGN KEY (ENERGY_TYPE) REFERENCES DIM_ENERGY_TYPE(ENERGY_TYPE_CODE)
);
CREATE INDEX IF NOT EXISTS IDX_CARBON_REGION_TYPE ON DIM_CARBON_FACTOR(REGION, ENERGY_TYPE);

-- =========================
-- Time-series (facts)
-- =========================
CREATE TABLE IF NOT EXISTS RAW_TIMESERIES (
    ID BIGINT IDENTITY PRIMARY KEY,
    POINT_ID BIGINT NOT NULL,
    TS TIMESTAMP NOT NULL,
    VALUE DECIMAL(20,6),
    QUALITY_FLAG VARCHAR(32),
    SOURCE_SYSTEM VARCHAR(64),
    INGEST_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_RAW_POINT FOREIGN KEY (POINT_ID) REFERENCES DIM_METER_POINT(POINT_ID)
);
CREATE INDEX IF NOT EXISTS IDX_RAW_POINT_TS ON RAW_TIMESERIES(POINT_ID, TS);
CREATE INDEX IF NOT EXISTS IDX_RAW_TS ON RAW_TIMESERIES(TS);

CREATE TABLE IF NOT EXISTS TS_MEASUREMENT (
    ID BIGINT IDENTITY PRIMARY KEY,
    POINT_ID BIGINT NOT NULL,
    TS TIMESTAMP NOT NULL,
    VALUE DECIMAL(20,6),
    QUALITY_FLAG VARCHAR(32),
    AGG_LEVEL VARCHAR(16),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TS_POINT FOREIGN KEY (POINT_ID) REFERENCES DIM_METER_POINT(POINT_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_TS_POINT_TS ON TS_MEASUREMENT(POINT_ID, TS);
CREATE INDEX IF NOT EXISTS IDX_TS_TS ON TS_MEASUREMENT(TS);

-- =========================
-- Alarm / monitoring
-- =========================
CREATE TABLE IF NOT EXISTS CFG_ALARM_RULE (
    RULE_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    NAME VARCHAR(128) NOT NULL,
    CATEGORY VARCHAR(64),
    EXPRESSION CLOB,
    THRESHOLD DECIMAL(18,6),
    SEVERITY VARCHAR(16),
    NOTIFICATION_GROUP VARCHAR(128),
    ENABLED CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT FK_RULE_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID)
);
CREATE UNIQUE INDEX IF NOT EXISTS UQ_RULE_PARK_NAME ON CFG_ALARM_RULE(PARK_ID, NAME);

CREATE TABLE IF NOT EXISTS EVT_ALARM (
    ALARM_ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    ENT_ID BIGINT,
    ASSET_ID BIGINT,
    LEVEL VARCHAR(16),
    CATEGORY VARCHAR(64),
    OBJECT_TYPE VARCHAR(32),
    OBJECT_ID BIGINT,
    START_TS TIMESTAMP NOT NULL,
    END_TS TIMESTAMP,
    STATUS VARCHAR(16),
    RULE_ID BIGINT,
    MESSAGE CLOB,
    ACK_BY VARCHAR(64),
    ACK_TS TIMESTAMP,
    CONSTRAINT FK_ALARM_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID),
    CONSTRAINT FK_ALARM_ENT FOREIGN KEY (ENT_ID) REFERENCES DIM_ENTERPRISE(ENT_ID),
    CONSTRAINT FK_ALARM_ASSET FOREIGN KEY (ASSET_ID) REFERENCES DIM_ASSET(ASSET_ID),
    CONSTRAINT FK_ALARM_RULE FOREIGN KEY (RULE_ID) REFERENCES CFG_ALARM_RULE(RULE_ID)
);
CREATE INDEX IF NOT EXISTS IDX_ALARM_PARK_START ON EVT_ALARM(PARK_ID, START_TS);
CREATE INDEX IF NOT EXISTS IDX_ALARM_ASSET ON EVT_ALARM(ASSET_ID);

CREATE TABLE IF NOT EXISTS DEF_KEY_MONITOR_POINT (
    ID BIGINT IDENTITY PRIMARY KEY,
    PARK_ID BIGINT NOT NULL,
    POINT_ID BIGINT NOT NULL,
    POINT_NAME VARCHAR(128),
    CATEGORY VARCHAR(64),
    CONSTRAINT FK_MONITOR_PARK FOREIGN KEY (PARK_ID) REFERENCES DIM_PARK(PARK_ID),
    CONSTRAINT FK_MONITOR_POINT FOREIGN KEY (POINT_ID) REFERENCES DIM_METER_POINT(POINT_ID)
);
CREATE INDEX IF NOT EXISTS IDX_MONITOR_PARK ON DEF_KEY_MONITOR_POINT(PARK_ID);

CREATE TABLE IF NOT EXISTS EVT_ACTION_RECO (
    RECO_ID BIGINT IDENTITY PRIMARY KEY,
    ALARM_ID BIGINT NOT NULL,
    RECO_TYPE VARCHAR(32),
    COMMAND_TEMPLATE CLOB,
    PRIORITY INT,
    CREATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(16),
    CONSTRAINT FK_RECO_ALARM FOREIGN KEY (ALARM_ID) REFERENCES EVT_ALARM(ALARM_ID)
);
CREATE INDEX IF NOT EXISTS IDX_RECO_ALARM ON EVT_ACTION_RECO(ALARM_ID);
